---
name: bhikers.club app beta for Android CI

on:
  push:
    tags:
      - 'v*'  # Runs only for version tags like v1.0.0
jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Nix
        uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: This is where the magic is happening
        shell: bash
        run: |
          set -x
          nix develop --impure --command flutter doctor
          # always clean & compile to enforce generated dart code is sane
          nix develop --impure --command make clean compile apk-release BUILD_NUMBER="${{ github.run_number }}" BUILD_NAME="${{ github.ref_name }}"
      - uses: parasitid/sign-android-release@v5
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: build/app/outputs/flutter-apk
          signingKeyBase64: ${{ secrets.KEYSTORE_JKS }}
          alias: github-bhiker
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEYSTORE_PASSWORD }}
      - name: Rename APK
        run:
          cp ${{steps.sign_app.outputs.signedReleaseFile}} \
            club.bhikers.bhikersclub_${{ github.ref_name }}+${{ github.run_number }}.apk
          cp ${{steps.sign_app.outputs.signedReleaseFile}} \
            club.bhikers.bhikersclub_latest.apk
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: "*.apk"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
